server:
  port: 8082

spring:
  application:
    name: loans-service

  datasource:
    url: jdbc:h2:mem:loans
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      readerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - feign.FeignException.NotFound

  retry:
    instances:
      readerService:
        max-attempts: 3
        wait-duration: 1s
        ignore-exceptions:
          - feign.FeignException.NotFound


management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers, retries
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG